### ISSUE TITLE
[BUG] Upgrade to version 2.4.0 made @shouldCall not working

### ISSUE THREAD

**Issue by radekbusa** [TinkoffCreditSystems/ng-event-plugins#29]
# 🐞 Bug report

### Description

Upgrade to ng-event-plugins@2.4.0 caused ShouldCalls in our application to throw this error:

```
ERROR TypeError: zone.run is not a function
    value tinkoff-ng-event-plugins.js:580
    ResizableSidebarComponent_mousemove_silent_HostBindingHandler ResizableSidebarComponent.js:8
    Angular 15
    addEventListener tinkoff-ng-event-plugins.js:344
    Angular 3
    addEventListener tinkoff-ng-event-plugins.js:341
    Angular 5
    ResizableSidebarComponent_HostBindings ResizableSidebarComponent.js:7
    Angular 4
    ClassificationSchemesComponent_Template template.html:1
    Angular 22
    RxJS 70
```

seems to be caused by should-call.ts:13, as if its associated init event did not pass Angular ZoneJS instance to it.

### Reproduction

In a controller of Angular component:
```
@HostListener('document:mousemove.silent', ['$event'])
@HostListener('document:init.mousemove', ['$event'])
@ShouldCall(resizeInProgress)
onSideResize(event: MouseEvent) { ... }
```

### Expected behavior

Nothing should be thrown.

### Versions

-   OS: MacOS 12
-   Browser Firefox and Chrome, both latest
-   Angular 13.0.2

### Additional context

-

**Comment by waterplea** [comment]
Could you try changing `document:init.mousemove` to `document:mousemove.init`?

**Comment by radekbusa** [comment]
Works like a charm. Sorry for misleading issue description, edited it. And sorry for bothering. Thanks!

**Comment by waterplea** [comment]
I believe this typo was in the readme at some point or it worked before. Glad it's solved 🙂
