### ISSUE TITLE
Demo app is not working [BUG] 

### ISSUE THREAD

**Issue by Olgagr** [TinkoffCreditSystems/ng-event-plugins#5]
# 🐞 Bug report

### Description

The demo app on codesandbox.io is not working. When the app is loaded the error is thrown

![image](https://user-images.githubusercontent.com/1297219/88285395-4976e480-ccef-11ea-919f-b9b8ab876577.png

### Reproduction

1. Click 'Demo' link in the README
2. You will be redirected to codesandbox.io and the error is shown

### Expected behavior

1. Demo is working

### Versions

-   OS: Ubuntu 18.04
-   Browser Firefox
-   Angular 8.2.4

**Comment by waterplea** [comment]
Seems to be an issue with Codesandbox. Thank you for reporting, will try to get it fixed!

**Comment by waterplea** [comment]
In the meantime, if you want to see it in action, you can pull this repo and do `npm i` + `npm start`

**Comment by sentika** [comment]
still not working tho

**Comment by waterplea** [comment]
Released version 2.0.0 which bumped Angular to version 9 during library compilation. This allowed to add a new plugin: `CaptureEventPlugin`. With it you can write listeners like that `(click.capture.stop)` to listen to events in capture phase (as they traverse down the DOM). Angular in demo was bumped to 11 to see that it properly works in the latest version as well. This also fixed interactive demo so closing this issue.
